kind: pipeline
name: default

steps:
  - name: Build Blog
    image: corylogan/blog-builder

    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - git remote set-url origin git@github.com:counterbeing/south-america-blog.git
      - mkdir -p  /root/.ssh
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519
      - chmod 0600 /root/.ssh/id_ed25519
      - eval "$(ssh-agent)"
      - ssh-add /root/.ssh/id_ed25519
      - git config --global user.email "ci@drone.corylogan.com"
      - git config --global user.name "Drone Server"

      - npm install
      - npm run build
      - git checkout rendered
      - rsync -avz dist/ ./

      - git add .
      - git commit -am "build $(date +'%Y/%m/%d %H:%M:%S:%3N')"
      - git push origin HEAD

branches:
  - master
